[build]
  # Directorio base donde est치 la aplicaci칩n
  base = "weather-app/"
  
  # Comando para construir la aplicaci칩n
  command = "npm run build"
  
  # Directorio que contiene los archivos construidos (relativo al base)
  publish = "dist"

# Configuraci칩n para que las rutas funcionen correctamente en una SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
